apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: backend-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./backend
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default