apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: frontend-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./frontend   # Path to the frontend directory
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
